[tool.black]
line-length = 79
exclude = '''
(
  /(  # generated files
    .github|
    .tox|
    .vscode|
    venv|
    .*/build/lib/.*|
    scripts|
    azure-monitor-opentelemetry/azure/monitor/opentelemetry/vendor|
  )/
)
'''
